title:            Earthson's Blog
tagline:          Stand Alone Complex
description:      Mad Man With Mad Things...
#Comment out url when working locally to resolve base urls correctly
#url: http://www.earthson.net

# Owner/author information
owner:
  name:           Earthson Lu
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          Earthson.Lu@gmail.com
#  twitter:        twnsndco        
  github:         Earthson       
#  instagram:      ctrunsthis     
#  dribbble:       coletownsend
#  disqus:         balzac
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
#  - title: Github
#    url: https://github.com/ColeTownsend/Balzac-for-Jekyll
#    external: true
#  - title: Cole Who?
#    url: http://coletownsend.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
#markdown:    redcarpet
markdown:    kramdown
markdown_ext: foo

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
